// src/config/defaultCategories.js
module.exports = [
  {
    category_id: "smart-li-ion-batteries",
    name: "Smart Lithium Ion Batteries",
    short_label: "Li-Ion",
    color_hex: "#F2706D",
    icon_url: "",
    is_popular: true,
    sort_order: 1,
  },
  {
    category_id: "smart-lithium-phosphate-battery",
    name: "Smart Lithium Phosphate Battery",
    short_label: "LiFePO4",
    color_hex: "#4CAF50",
    icon_url: "",
    is_popular: true,
    sort_order: 2,
  },
  {
    category_id: "scooty-batteries",
    name: "Scooty Batteries",
    short_label: "Scooty",
    color_hex: "#2196F3",
    icon_url: "",
    is_popular: true,
    sort_order: 3,
  },
  {
    category_id: "electric-cycle-batteries",
    name: "Electric Cycle Batteries",
    short_label: "E-Cycle",
    color_hex: "#FF9800",
    icon_url: "",
    is_popular: false,
    sort_order: 4,
  },
  {
    category_id: "smart-integrated-inverters",
    name: "Smart Integrated Inverters",
    short_label: "Inverter",
    color_hex: "#9C27B0",
    icon_url: "",
    is_popular: true,
    sort_order: 5,
  },
  {
    category_id: "bms",
    name: "BMS",
    short_label: "BMS",
    color_hex: "#795548",
    icon_url: "",
    is_popular: false,
    sort_order: 6,
  },
  {
    category_id: "bike-batteries",
    name: "Bike Batteries",
    short_label: "Bike",
    color_hex: "#009688",
    icon_url: "",
    is_popular: false,
    sort_order: 7,
  },
  {
    category_id: "car-batteries",
    name: "Car Batteries",
    short_label: "Car",
    color_hex: "#607D8B",
    icon_url: "",
    is_popular: false,
    sort_order: 8,
  },
];
